display_errors=Off
log_errors=On
error_reporting=E_ALL
expose_php=Off

upload_max_filesize=20M
post_max_size=21M
max_file_uploads=20
file_uploads=On

session.cookie_httponly=1
session.use_strict_mode=1
session.cookie_samesite=Lax

date.timezone=America/Bogota
