-- Tablas y columnas que usa la app y no vinieron en postgres_inv.sql

CREATE TABLE IF NOT EXISTS inv_form_categorias (
  "id_categoria" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" varchar(100) NOT NULL,
  "Estado" varchar(20) NOT NULL DEFAULT 'Activo' CHECK ("Estado" IN ('Activo','Inactivo','Eliminado'))
);

INSERT INTO inv_form_categorias ("Nombre", "Estado")
SELECT 'General', 'Activo'
WHERE NOT EXISTS (SELECT 1 FROM inv_form_categorias LIMIT 1);

ALTER TABLE inv_form_inventario
  ADD COLUMN IF NOT EXISTS "id_categoria" integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_inv_categoria'
  ) THEN
    ALTER TABLE inv_form_inventario
      ADD CONSTRAINT fk_inv_categoria
      FOREIGN KEY ("id_categoria") REFERENCES inv_form_categorias ("id_categoria") ON UPDATE CASCADE;
  END IF;
END $$;

UPDATE inv_form_inventario
SET "id_categoria" = (SELECT "id_categoria" FROM inv_form_categorias ORDER BY "id_categoria" LIMIT 1)
WHERE "id_categoria" IS NULL;

ALTER TABLE inv_form_movimientos
  ADD COLUMN IF NOT EXISTS "Consecutivo" integer;

UPDATE inv_form_movimientos m
SET "Consecutivo" = sub.n
FROM (
  SELECT "id_movimiento",
         ROW_NUMBER() OVER (PARTITION BY "Tipo" ORDER BY "id_movimiento") AS n
  FROM inv_form_movimientos
) sub
WHERE m."id_movimiento" = sub."id_movimiento"
  AND m."Consecutivo" IS NULL;

ALTER TABLE inv_form_movimientos
  ALTER COLUMN "Consecutivo" SET DEFAULT 1;

UPDATE inv_form_movimientos SET "Consecutivo" = 1 WHERE "Consecutivo" IS NULL;

DO $$
BEGIN
  ALTER TABLE inv_form_movimientos DROP CONSTRAINT IF EXISTS inv_form_movimientos_Tipo_check;
  ALTER TABLE inv_form_movimientos
    ADD CONSTRAINT inv_form_movimientos_Tipo_check
    CHECK ("Tipo" IN ('Ingreso','Prestamo','Devolucion','Dar_Baja'));
EXCEPTION WHEN others THEN
  NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE inv_form_inventario DROP CONSTRAINT IF EXISTS inv_form_inventario_Estado_check;
  ALTER TABLE inv_form_inventario
    ADD CONSTRAINT inv_form_inventario_Estado_check
    CHECK ("Estado" IN ('Activo','Inactivo','Eliminado'));
EXCEPTION WHEN others THEN
  NULL;
END $$;

CREATE TABLE IF NOT EXISTS inv_form_movimiento_fotos (
  "id_foto" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_movimiento" integer NOT NULL REFERENCES inv_form_movimientos ("id_movimiento") ON DELETE CASCADE,
  "Ruta" varchar(500) NOT NULL,
  "Orden" smallint NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS inv_form_solicitudes_prestamo (
  "id_solicitud" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Cedula_solicitante" varchar(20) NOT NULL REFERENCES inv_form_usuarios ("Cedula") ON UPDATE CASCADE,
  "Fecha_solicitud" date NOT NULL,
  "Descripcion" text,
  "Estado" varchar(20) NOT NULL DEFAULT 'Pendiente' CHECK ("Estado" IN ('Pendiente','Aprobada','Rechazada','Cancelada')),
  "id_movimiento" integer REFERENCES inv_form_movimientos ("id_movimiento") ON DELETE SET NULL,
  "Cedula_aprobador" varchar(20) REFERENCES inv_form_usuarios ("Cedula") ON UPDATE CASCADE,
  "Fecha_resolucion" timestamptz,
  "Motivo_rechazo" text
);

CREATE TABLE IF NOT EXISTS inv_form_det_solicitudes (
  "id_detalle" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_solicitud" integer NOT NULL REFERENCES inv_form_solicitudes_prestamo ("id_solicitud") ON DELETE CASCADE,
  "id_linea" integer NOT NULL DEFAULT 1,
  "Codigo_elemento" varchar(50) NOT NULL REFERENCES inv_form_inventario ("Codigo") ON UPDATE CASCADE,
  "Cantidad" integer NOT NULL DEFAULT 1
);

INSERT INTO inv_form_usuarios ("Cedula", "Nombres", "Password", "Tipo", "Estado")
VALUES (
  'admin',
  'Administrador Sistema',
  '$2y$10$yfePygccbF.AC6m3bToDieNycmq2ZJXoSW9AXvKCwCBsnZ.P3tU.G',
  'Admin',
  'Activo'
)
ON CONFLICT ("Cedula") DO NOTHING;

ALTER TABLE inv_form_usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE inv_form_categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE inv_form_inventario ENABLE ROW LEVEL SECURITY;
ALTER TABLE inv_form_movimientos ENABLE ROW LEVEL SECURITY;
ALTER TABLE inv_form_det_movimientos ENABLE ROW LEVEL SECURITY;
ALTER TABLE inv_form_movimiento_fotos ENABLE ROW LEVEL SECURITY;
ALTER TABLE inv_form_solicitudes_prestamo ENABLE ROW LEVEL SECURITY;
ALTER TABLE inv_form_det_solicitudes ENABLE ROW LEVEL SECURITY;
ALTER TABLE inv_form_cuentadantes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS inv_form_usuarios_all ON inv_form_usuarios;
DROP POLICY IF EXISTS inv_form_categorias_all ON inv_form_categorias;
DROP POLICY IF EXISTS inv_form_inventario_all ON inv_form_inventario;
DROP POLICY IF EXISTS inv_form_movimientos_all ON inv_form_movimientos;
DROP POLICY IF EXISTS inv_form_det_movimientos_all ON inv_form_det_movimientos;
DROP POLICY IF EXISTS inv_form_movimiento_fotos_all ON inv_form_movimiento_fotos;
DROP POLICY IF EXISTS inv_form_solicitudes_all ON inv_form_solicitudes_prestamo;
DROP POLICY IF EXISTS inv_form_det_solicitudes_all ON inv_form_det_solicitudes;
DROP POLICY IF EXISTS inv_form_cuentadantes_all ON inv_form_cuentadantes;

CREATE POLICY inv_form_usuarios_all ON inv_form_usuarios FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY inv_form_categorias_all ON inv_form_categorias FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY inv_form_inventario_all ON inv_form_inventario FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY inv_form_movimientos_all ON inv_form_movimientos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY inv_form_det_movimientos_all ON inv_form_det_movimientos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY inv_form_movimiento_fotos_all ON inv_form_movimiento_fotos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY inv_form_solicitudes_all ON inv_form_solicitudes_prestamo FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY inv_form_det_solicitudes_all ON inv_form_det_solicitudes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY inv_form_cuentadantes_all ON inv_form_cuentadantes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

GRANT ALL ON inv_form_usuarios, inv_form_categorias, inv_form_inventario, inv_form_movimientos,
  inv_form_det_movimientos, inv_form_movimiento_fotos, inv_form_solicitudes_prestamo,
  inv_form_det_solicitudes, inv_form_cuentadantes
  TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
