-- Agenda de portátiles (prefijo inv_form_). Visible en calendario para todos los usuarios.

CREATE TABLE IF NOT EXISTS inv_form_agenda_computadores (
  "id_agenda" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Cedula_solicitante" varchar(20) NOT NULL REFERENCES inv_form_usuarios ("Cedula") ON UPDATE CASCADE,
  "Nombres" varchar(150) NOT NULL,
  "Telefono" varchar(20) NOT NULL,
  "Fecha_solicitud" date NOT NULL,
  "Cantidad_portatiles" integer NOT NULL CHECK ("Cantidad_portatiles" >= 1),
  "Sede" varchar(20) NOT NULL CHECK ("Sede" IN ('Ternera', 'Emprender')),
  "Hora_inicio" time NOT NULL,
  "Hora_final" time NOT NULL,
  "Ficha_programa" varchar(150) NOT NULL,
  "Estado" varchar(20) NOT NULL DEFAULT 'Pendiente'
    CHECK ("Estado" IN ('Pendiente', 'Aprobada', 'Rechazada', 'Cancelada', 'Reprogramada')),
  "Cedula_aprobador" varchar(20) REFERENCES inv_form_usuarios ("Cedula") ON UPDATE CASCADE,
  "Fecha_resolucion" timestamptz,
  "Motivo_rechazo" text,
  "Fecha_original" date,
  "Hora_inicio_original" time,
  "Hora_final_original" time,
  "Motivo_reprogramacion" text,
  CONSTRAINT agenda_computadores_horario CHECK ("Hora_final" > "Hora_inicio")
);

ALTER TABLE inv_form_agenda_computadores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS inv_form_agenda_computadores_all ON inv_form_agenda_computadores;
CREATE POLICY inv_form_agenda_computadores_all ON inv_form_agenda_computadores
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

GRANT ALL ON inv_form_agenda_computadores TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
