-- Esquema del inventario en Supabase (SQL Editor).
-- Tablas con prefijo inv_form_ y políticas permisivas para la anon key.
-- El login de la aplicación sigue siendo el de PHP (tabla Usuarios).

create table if not exists inv_form_usuarios (
    "Cedula" varchar(20) primary key,
    "Nombres" varchar(150) not null,
    "Password" varchar(255) not null,
    "Tipo" varchar(20) not null default 'Usuario' check ("Tipo" in ('Admin', 'Usuario')),
    "Estado" varchar(20) not null default 'Activo' check ("Estado" in ('Activo', 'Inactivo'))
);

create table if not exists inv_form_categorias (
    "id_categoria" integer generated by default as identity primary key,
    "Nombre" varchar(100) not null,
    "Estado" varchar(20) not null default 'Activo' check ("Estado" in ('Activo', 'Inactivo', 'Eliminado'))
);

create table if not exists inv_form_inventario (
    "Codigo" varchar(50) primary key,
    "Elemento" varchar(150) not null,
    "id_categoria" integer references inv_form_categorias ("id_categoria") on update cascade,
    "Descripcion" text,
    "Cantidad" integer not null default 0,
    "Fotografia" varchar(500),
    "Estado" varchar(20) not null default 'Activo' check ("Estado" in ('Activo', 'Inactivo', 'Eliminado'))
);

create table if not exists inv_form_movimientos (
    "id_movimiento" integer generated by default as identity primary key,
    "Tipo" varchar(20) not null check ("Tipo" in ('Ingreso', 'Prestamo', 'Devolucion', 'Dar_Baja')),
    "Consecutivo" integer not null,
    "Fecha" date not null,
    "Cedula_cuentadante" varchar(20) references inv_form_usuarios ("Cedula") on update cascade,
    "Descripcion" text,
    "Estado" varchar(20) not null default 'Activo' check ("Estado" in ('Activo', 'Inactivo', 'Cerrado')),
    "id_movimiento_ref" integer references inv_form_movimientos ("id_movimiento") on delete set null
);

create table if not exists inv_form_det_movimientos (
    "Consecutivo" integer generated by default as identity primary key,
    "id_movimiento" integer not null references inv_form_movimientos ("id_movimiento") on delete cascade,
    "id_Detalle" integer not null default 1,
    "Codigo_elemento" varchar(50) not null references inv_form_inventario ("Codigo") on update cascade,
    "Cantidad" integer not null default 1,
    "Estado" varchar(20) not null default 'Activo' check ("Estado" in ('Activo', 'Inactivo'))
);

create table if not exists inv_form_movimiento_fotos (
    "id_foto" integer generated by default as identity primary key,
    "id_movimiento" integer not null references inv_form_movimientos ("id_movimiento") on delete cascade,
    "Ruta" varchar(500) not null,
    "Orden" smallint not null default 1
);

create table if not exists inv_form_solicitudes_prestamo (
    "id_solicitud" integer generated by default as identity primary key,
    "Cedula_solicitante" varchar(20) not null references inv_form_usuarios ("Cedula") on update cascade,
    "Fecha_solicitud" date not null,
    "Descripcion" text,
    "Estado" varchar(20) not null default 'Pendiente' check ("Estado" in ('Pendiente', 'Aprobada', 'Rechazada', 'Cancelada')),
    "id_movimiento" integer references inv_form_movimientos ("id_movimiento") on delete set null,
    "Cedula_aprobador" varchar(20) references inv_form_usuarios ("Cedula") on update cascade,
    "Fecha_resolucion" timestamptz,
    "Motivo_rechazo" text
);

create table if not exists inv_form_det_solicitudes (
    "id_detalle" integer generated by default as identity primary key,
    "id_solicitud" integer not null references inv_form_solicitudes_prestamo ("id_solicitud") on delete cascade,
    "id_linea" integer not null default 1,
    "Codigo_elemento" varchar(50) not null references inv_form_inventario ("Codigo") on update cascade,
    "Cantidad" integer not null default 1
);

insert into inv_form_categorias ("Nombre", "Estado")
select 'General', 'Activo'
where not exists (select 1 from inv_form_categorias limit 1);

-- Password por defecto: 123456
insert into inv_form_usuarios ("Cedula", "Nombres", "Password", "Tipo", "Estado")
values (
    'admin',
    'Administrador Sistema',
    '$2y$10$yfePygccbF.AC6m3bToDieNycmq2ZJXoSW9AXvKCwCBsnZ.P3tU.G',
    'Admin',
    'Activo'
)
on conflict ("Cedula") do nothing;

alter table inv_form_usuarios enable row level security;
alter table inv_form_categorias enable row level security;
alter table inv_form_inventario enable row level security;
alter table inv_form_movimientos enable row level security;
alter table inv_form_det_movimientos enable row level security;
alter table inv_form_movimiento_fotos enable row level security;
alter table inv_form_solicitudes_prestamo enable row level security;
alter table inv_form_det_solicitudes enable row level security;

drop policy if exists inv_form_usuarios_all on inv_form_usuarios;
drop policy if exists inv_form_categorias_all on inv_form_categorias;
drop policy if exists inv_form_inventario_all on inv_form_inventario;
drop policy if exists inv_form_movimientos_all on inv_form_movimientos;
drop policy if exists inv_form_det_movimientos_all on inv_form_det_movimientos;
drop policy if exists inv_form_movimiento_fotos_all on inv_form_movimiento_fotos;
drop policy if exists inv_form_solicitudes_all on inv_form_solicitudes_prestamo;
drop policy if exists inv_form_det_solicitudes_all on inv_form_det_solicitudes;

create policy inv_form_usuarios_all on inv_form_usuarios for all to anon, authenticated using (true) with check (true);
create policy inv_form_categorias_all on inv_form_categorias for all to anon, authenticated using (true) with check (true);
create policy inv_form_inventario_all on inv_form_inventario for all to anon, authenticated using (true) with check (true);
create policy inv_form_movimientos_all on inv_form_movimientos for all to anon, authenticated using (true) with check (true);
create policy inv_form_det_movimientos_all on inv_form_det_movimientos for all to anon, authenticated using (true) with check (true);
create policy inv_form_movimiento_fotos_all on inv_form_movimiento_fotos for all to anon, authenticated using (true) with check (true);
create policy inv_form_solicitudes_all on inv_form_solicitudes_prestamo for all to anon, authenticated using (true) with check (true);
create policy inv_form_det_solicitudes_all on inv_form_det_solicitudes for all to anon, authenticated using (true) with check (true);

grant all on inv_form_usuarios, inv_form_categorias, inv_form_inventario, inv_form_movimientos,
    inv_form_det_movimientos, inv_form_movimiento_fotos, inv_form_solicitudes_prestamo, inv_form_det_solicitudes
    to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into storage.buckets (id, name, public)
values ('productos', 'productos', true)
on conflict (id) do update set public = true;

drop policy if exists inv_form_storage_all on storage.objects;
create policy inv_form_storage_all on storage.objects
    for all to anon, authenticated
    using (bucket_id = 'productos')
    with check (bucket_id = 'productos');

